name: prism_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  fl_chart: ^1.2.0
  font_awesome_flutter: ^11.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  lottie: ^3.3.2
  curved_navigation_bar: ^1.0.6
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.2.2

  # Compatible Firebase Suite
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.2.2

  flutter_local_notifications: ^17.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  material_symbols_icons: ^4.2928.0
  flutter_bloc: ^9.1.1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.6
  flutter_svg: ^2.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_light.svg
    - assets/logo_dark.svg
    - assets/google.svg
    - assets/facebook.svg
    - assets/pig_light.svg
    - assets/pig_dark.svg
    - assets/lottie/prism.json
    - assets/lottie/prism_dark.json
    - assets/LP_darkmode.png
    - assets/LP_lightmode.png

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/prism_logo.svg
  image_dark: assets/prism_logo_dark.svg
  android: true
  ios: true
  web: true
