// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDu6tAG0VauEOmpp9xrZ4Ct9AlPE2qd24',
    appId: '1:666163168561:web:f4c9acc296f7ff7db29c10',
    messagingSenderId: '666163168561',
    projectId: 'prism-3cd2c',
    authDomain: 'prism-3cd2c.firebaseapp.com',
    storageBucket: 'prism-3cd2c.firebasestorage.app',
    measurementId: 'G-ZT20M4HJ83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5vjNWD5eHZOSD9-GdcW9yCJqqcg6e0Wo',
    appId: '1:666163168561:android:c4d84b253610721eb29c10',
    messagingSenderId: '666163168561',
    projectId: 'prism-3cd2c',
    storageBucket: 'prism-3cd2c.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDu6tAG0VauEOmpp9xrZ4Ct9AlPE2qd24',
    appId: '1:666163168561:web:4a3d315576664fb9b29c10',
    messagingSenderId: '666163168561',
    projectId: 'prism-3cd2c',
    authDomain: 'prism-3cd2c.firebaseapp.com',
    storageBucket: 'prism-3cd2c.firebasestorage.app',
    measurementId: 'G-65RJYKNPZQ',
  );
}
